apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: react-app

  template:
    metadata:
      labels:
        app: react-app

    spec:
      containers:
      - name: react-app-container
        image: sevenajay/2048:latest

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service

spec:
  selector:
    app: react-app

  type: NodePort

  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
